spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sgcc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: yuser
    password: 11123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 启用监控页面
      stat-view-servlet:
        enabled: true
      # 启用ConfigFilter
      filter:
        config:
          enabled: true
      # 配置 connection-properties，启用加密，配置公钥。
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
    #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 5
    #最小连接池数量
    minIdle: 5
    #最大连接池数量
    maxActive: 20
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，
    #如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    #Destroy线程会检测连接的间隔时间
    #testWhileIdle的判断依据
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
# druid生成的公钥
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIMyBQ2rVsGNXmf6nGg2p4e/QaRhNhbYGW0PYE03bHEAlHVFUkhdDprfWvLlpppcCGvE93e0CAwEAAQ==